language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - TEST_COMMAND="./vendor/bin/simple-phpunit"

branches:
    except:
        - /^analysis-.*$/

matrix:
    fast_finish: true
    include:
          # Test with lowest dependencies
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak"

          # Test the latest stable release
        - php: 7.2
          env: COVERAGE=true TEST_COMMAND="./vendor/bin/simple-phpunit --coverage-text --coverage-clover=coverage.clover"
        - php: 7.3
        - php: 7.4

          # Force some major versions of Symfony
        - php: 7.2
          env: DEPENDENCIES="dunglas/symfony-lock:^4"

          # Latest commit to master
        - php: 7.2
          env: STABILITY="dev"

    allow_failures:
          # Dev-master is allowed to fail.
        - env: STABILITY="dev"
        - php: hhvm

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -z "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
    - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    - $TEST_COMMAND

after_success:
    - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
